---
###########################################################################
# CONFIGURATION                                                           #
###########################################################################

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: default.yml
  when: openssh_loaded_os_family|default(False) == False

- name: Configure OpenSSH - sshd_config
  template: dest=/etc/ssh/sshd_config owner=root group=root mode=0600 backup=yes
  first_available_file:
    - "{{ ansible_hostname }}_sshd_config.j2"
    - sshd_config.j2
  notify:
    - sshd - restart service
  when: openssh_loaded_os_family|default(False) != False

- name: Configure OpenSSH - Banner
  template: dest=/etc/issue.net owner=root group=root mode=0644 backup=no
  first_available_file:
    - "{{ ansible_hostname }}_issue_net.j2"
    - issue_net.j2
  notify:
    - sshd - restart service
  when: openssh_loaded_os_family|default(False) != False

- name: Ensure OpenSSH is configured to start on boot
  service:
    name: "{{ opensshd_init_name[ansible_os_family] }}"
    enabled: yes
