---
  - name: 6.1.1 Enable anacron Daemon (Scored)
    yum: >
      name=cronie-anacron
      state=present
    tags:
      - scored
      - section6.1
      - section6.1.1

  - name: 6.1.2 Enable crond Daemon (Scored)
    service: >
      name=crond
      enabled=yes
      state=started
    tags:
      - scored
      - section6.1
      - section6.1.2

  - name: 6.1.3 Set User/Group Owner and Permission on /etc/anacrontab (Scored)
    file: >
      path=/etc/anacrontab
      owner=root
      group=root
      mode=0600
    tags:
      - scored
      - section6.1
      - section6.1.3

  - name: 6.1.4 Set User/Group Owner and Permission on /etc/crontab (Scored)
    file: >
      path=/etc/crontab
      owner=root
      group=root
      mode=0600
    tags:
      - scored
      - section6.1
      - section6.1.4

  - name: 6.1.5 Set User/Group Owner and Permission on /etc/cron.hourly (Scored)
    file: >
      path=/etc/cron.hourly
      owner=root
      group=root
      mode=0600
    tags:
      - scored
      - section6.1
      - section6.1.5

  - name: 6.1.6 Set User/Group Owner and Permission on /etc/cron.daily  (Scored)
    file: >
      path=/etc/cron.daily
      owner=root
      group=root
      mode=0600
    tags:
      - scored
      - section6.1
      - section6.1.6

  - name: 6.1.7 Set User/Group Owner and Permission on /etc/cron.weekly  (Scored)
    file: >
      path=/etc/cron.weekly
      owner=root
      group=root
      mode=0600
    tags:
      - scored
      - section6.1
      - section6.1.7

  - name: 6.1.8 Set User/Group Owner and Permission on /etc/cron.monthly (Scored)
    file: >
      path=/etc/cron.monthly
      owner=root
      group=root
      mode=0600
    tags:
      - scored
      - section6.1
      - section6.1.8

  - name: 6.1.9 Set User/Group Owner and Permission on /etc/cron.d (Scored)
    file: >
      path=/etc/cron.d
      state=directory
      owner=root
      group=root
      mode=0700
    tags:
      - scored
      - section6.1
      - section6.1.9

  - name: 6.1.10 Restrict at Daemon (Scored)
    file: >
      path=/etc/at.deny
      state=absent
    tags:
      - scored
      - section6.1
      - section6.1.10

  - name: 6.1.10 Restrict at Daemon (Scored)
    file: >
      path=/etc/at.allow
      state=touch
      owner=root
      group=root
      mode=0600
    tags:
      - scored
      - section6.1
      - section6.1.10

  - name: 6.1.11 Restrict at/cron to Authorized Users (Scored)
    file: >
      path=/etc/cron.deny
      state=absent
    tags:
      - scored
      - section6.1
      - section6.1.11

  - name: 6.1.11 Restrict at/cron to Authorized Users (Scored)
    file: >
      path=/etc/cron.allow
      state=touch
      owner=root
      group=root
      mode=0600
    tags:
      - scored
      - section6.1
      - section6.1.11

  - include: redhat.yml
    when: ansible_os_family == 'RedHat'

  - include: default.yml
    when: openssh_loaded_os_family|default(False) == False

  - name: 6.2 - Configure OpenSSH - sshd_config
    template: dest=/etc/ssh/sshd_config owner=root group=root mode=0600 backup=yes
    first_available_file:
      - "{{ ansible_hostname }}_sshd_config.j2"
      - sshd_config.j2
    notify:
      - sshd - restart service
    when: openssh_loaded_os_family|default(False) != False
    tags:
      - scored
      - section6.2

  - name: 6.2 - Configure OpenSSH - Banner
    template: dest=/etc/issue.net owner=root group=root mode=0644 backup=no
    first_available_file:
      - "{{ ansible_hostname }}_issue_net.j2"
      - issue_net.j2
    notify:
      - sshd - restart service
    when: openssh_loaded_os_family|default(False) != False
    tags:
      - scored
      - section6.2

  - name: 6.2 - Ensure OpenSSH is configured to start on boot
    service:
      name: "{{ opensshd_init_name[ansible_os_family] }}"
      enabled: yes
    tags:
      - scored
      - section6.2

  - name: 6.2 -  Configure SSH  (Scored)
    debug: msg="*** SSH has been configured."
    tags:
      - scored
      - section6.2
      - section6.2.1
      - section6.2.2
      - section6.2.3
      - section6.2.4
      - section6.2.5
      - section6.2.6
      - section6.2.7
      - section6.2.8
      - section6.2.9
      - section6.2.10
      - section6.2.11
      - section6.2.12
      - section6.2.13
      - section6.2.14    

  - name: 6.3.2 - 6.3.4 Configure PAM (Scored)
    debug: msg="*** Not relevant."
    tags:
      - scored
      - section6.3
      - section6.3.2
      - section6.3.3
      - section6.3.4

  - name: 6.5 Restrict Access to the su Command (Scored)
    debug: msg="*** Not relevant."
    tags:
      - scored
      - section6.5

