---
  - name: 7.1.1 Set Password Expiration Days (Scored)
    lineinfile: >
      backup=yes 
      state=present 
      dest=/etc/login.defs
      backrefs=yes
      regexp="^PASS_MAX_DAYS\s+"
      line="PASS_MAX_DAYS\t90"
    tags:
      - scored
      - section7.1
      - section7.1.1

  - name: 7.1.2 Set Password Change Minimum Number of Days (Scored)
    lineinfile: >
      backup=yes 
      state=present 
      dest=/etc/login.defs
      backrefs=yes
      regexp="^PASS_MIN_DAYS\s+"
      line="PASS_MIN_DAYS\t7"
    tags:
      - scored
      - section7.1
      - section7.1.2

  - name: 7.1.3 Set Password Expiring Warning Days (Scored)
    lineinfile: >
      backup=yes 
      state=present 
      dest=/etc/login.defs
      backrefs=yes
      regexp="^PASS_WARN_AGE\s+"
      line="PASS_WARN_AGE\t7"
    tags:
      - scored
      - section7.1
      - section7.1.3

  - name: 7.2 Disable System Accounts (Scored) - preparation
    debug: msg="*** Not relevant."
    tags:
      - scored
      - section7.2

  - name: 7.3 Set Default Group for root Account (Scored)
    debug: msg="*** Not relevant."
    tags:
      - scored
      - section7.3

  - name: 7.4 Set Default umask for Users (Scored)
    debug: msg="*** Not relevant."
    tags:
      - scored
      - section7.4

  - name: 7.5 Lock Inactive User Accounts (Scored)
    command: /usr/sbin/useradd -D -f 35
    when: lock_inactive
    tags:
      - scored
      - section7.5
