---
  - name: Create /etc/modprobe.d/CIS.conf with root ownership & mode
    file: path=/etc/modprobe.d/CIS.conf state=touch owner=root group=root mode=0600
    changed_when: false
    tags:
      - notscored
      - section1.1
      - section1.1.18
      - section1.1.19
      - section1.1.20
      - section1.1.21
      - section1.1.22
      - section1.1.23
      - section1.1.24

  - name: 1.1.18 Disable Mounting of cramfs Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install cramfs /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.18

  - name: 1.1.19 Disable Mounting of freevxfs Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install freevxfs /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.19

  - name: 1.1.20 Disable Mounting of jffs2 Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install jffs2 /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.20

  - name: 1.1.21 Disable Mounting of hfs Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install hfs /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.21

  - name: 1.1.22 Disable Mounting of hfsplus Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install hfsplus /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.22

  - name: 1.1.23 Disable Mounting of squashfs Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install squashfs /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.23

  - name: 1.1.24 Disable Mounting of udf Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install udf /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.24

  - name: 1.3.1-1.3.2 Install AIDE (Not Scored)
    debug: msg="*** OSSEC needs to be installed instead."
    tags:
      - notscored
      - section1.3
      - section1.3.1
      - section1.3.2

  - name: 1.4.1-1.4.7 Enable and Configure SELinux (Not Scored)
    debug: msg="*** SELinux is not used for now."
    tags:
      - notscored
      - section1.4
      - section1.4.1
      - section1.4.2
      - section1.4.3
      - section1.4.4
      - section1.4.5
      - section1.4.6
      - section1.4.7
