---
  - name: 5.2.1.1 Configure Data Retention (Not Scored)
    debug: msg="*** Not relevant."
    tags:
      - notscored
      - section5.2
      - section5.2.1
      - section5.2.1.1

  - name: 5.2.1.2 Disable System on Audit Log Full (Not Scored)
    debug: msg="*** Not relevant."
    tags:
      - notscored
      - section5.2
      - section5.2.1
      - section5.2.1.2

  - name: 5.2.1.2 Disable System on Audit Log Full (Not Scored)
    debug: msg="*** Not relevant."
    tags:
      - notscored
      - section5.2
      - section5.2.1
      - section5.2.1.2

  - name: 5.2.1.2 Disable System on Audit Log Full (Not Scored)
    debug: msg="*** Not relevant."
    tags:
      - notscored
      - section5.2
      - section5.2.1
      - section5.2.1.2

  - name: 5.2.1.3 Keep All Auditing Information (Scored)
    debug: msg="*** Not relevant."
    tags:
      - scored
      - section5.2
      - section5.2.1
      - section5.2.1.3

  - name: 5.2.2 Enable auditd Service (Scored)
    service: >
      name=auditd
      enabled=yes
      state=running
    tags:
      - scored
      - section5.2
      - section5.2.2

  - name: 5.2.3 Enable Auditing for Processes That Start Prior to auditd (Scored)
    debug: msg="*** Not relevant."
    tags:
      - scored
      - section5.2
      - section5.2.3

  - name: 5.2.4 - 5.2.18 Configure auditd Rules (Scored)
    copy: >
      src=etc/audit/syslog.conf
      dest=/etc/audisp/plugins.d/syslog.conf
    notify: restart auditd
    tags:
      - scored
      - section5.2
      - section5.2.4
      - section5.2.5
      - section5.2.6
      - section5.2.7
      - section5.2.8
      - section5.2.9
      - section5.2.10
      - section5.2.11
      - section5.2.12
      - section5.2.13
      - section5.2.14
      - section5.2.15
      - section5.2.16
      - section5.2.17
      - section5.2.18

  - name: 5.2.4 - 5.2.18 Configure auditd Rules (Scored)
    copy: >
      src=etc/audit/audit.rules
      dest=/etc/audit/audit.rules
    notify: restart auditd
    tags:
      - scored
      - section5.2
      - section5.2.4
      - section5.2.5
      - section5.2.6
      - section5.2.7
      - section5.2.8
      - section5.2.9
      - section5.2.10
      - section5.2.11
      - section5.2.12
      - section5.2.13
      - section5.2.14
      - section5.2.15
      - section5.2.16
      - section5.2.17
      - section5.2.18
