---

  - name: 9.1.2 Verify Permissions on /etc/passwd (Scored)
    file: >
      path=/etc/passwd
      mode=0644
    tags:
      - scored
      - section9.1
      - section9.1.2

  - name: 9.1.3 Verify Permissions on /etc/shadow (Scored)
    file: >
      path=/etc/shadow
      mode=0000
    tags:
      - scored
      - section9.1
      - section9.1.3

  - name: 9.1.4 Verify Permissions on /etc/gshadow (Scored)
    file: >
      path=/etc/gshadow
      mode=0000
    tags:
      - scored
      - section9.1
      - section9.1.4

  - name: 9.1.5 Verify Permissions on /etc/group (Scored)
    file: >
      path=/etc/group
      mode=0644
    tags:
      - scored
      - section9.1
      - section9.1.5

  - name: 9.1.6 Verify User/Group Ownership on /etc/passwd (Scored)
    file: >
      path=/etc/passwd
      owner=root
      group=root
    tags:
      - scored
      - section9.1
      - section9.1.6

  - name: 9.1.7 Verify User/Group Ownership on /etc/shadow (Scored)
    file: >
      path=/etc/shadow
      owner=root
      group=root
    tags:
      - scored
      - section9.1
      - section9.1.7

  - name: 9.1.8 Verify User/Group Ownership on /etc/gshadow (Scored)
    file: >
      path=/etc/gshadow
      owner=root
      group=root
    tags:
      - scored
      - section9.1
      - section9.1.8

  - name: 9.1.9 Verify User/Group Ownership on /etc/group (Scored)
    file: >
      path=/etc/group
      owner=root
      group=root
    tags:
      - scored
      - section9.1
      - section9.1.9

  - name: 9.1.10 Find World Writable Files (Not Scored)
    shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -0002"
    when: verify_find
    tags:
      - notscored
      - section9.1
      - section9.1.10

  - name: 9.1.11 Find Un-owned Files and Directories (Scored)
    shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser -ls"
    when: verify_find
    tags:
      - scored
      - section9.1
      - section9.1.11

  - name: 9.1.12 Find Un-grouped Files and Directories (Scored)
    shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nogroup -ls"
    when: verify_find
    tags:
      - scored
      - section9.1
      - section9.1.12

  - name: 9.1.13 Find SUID System Executables (Not Scored)
    shell: '/bin/rpm -V `/bin/rpm -qf /usr/bin/sudo`'
    register: suid
    when: verify_rpm
    tags:
      - notscored
      - section9.1
      - section9.1.13

  - name: 9.1.14 Find SGID System Executables (Not Scored)
    shell: '/bin/rpm -V `/bin/rpm -qf /usr/bin/sudo`'
    register: sgid
    when: verify_rpm
    tags:
      - notscored
      - section9.1
      - section9.1.14

  - name: 9.2.1 - 9.2.19 System Maintenance
    debug: msg="*** Not relevant."
    tags:
      - scored
      - section9.2
      - section9.2.1
      - section9.2.2
      - section9.2.3
      - section9.2.4
      - section9.2.5
      - section9.2.6
      - section9.2.7
      - section9.2.8
      - section9.2.9
      - section9.2.10
      - section9.2.11
      - section9.2.12
      - section9.2.13
      - section9.2.14
      - section9.2.15
      - section9.2.16
      - section9.2.17
      - section9.2.18
      - section9.2.19
      - section9.2.20
