---
- name: "installing repository gpg (redhat)"
  action: rpm_key state=present key=http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX

- name: "installing repository rpm (redhat)"
  action: yum pkg={{item}} state=installed
  with_items:
    - http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm

- name: "check packages (redhat)"
  action: yum pkg={{ item }} state=present
  with_items: zabbix_agent_packages
