---
  - name:  restart auditd
    service: name=auditd state=restarted

  - name: rsyslog - restart service
    service: name=rsyslog state=restarted

  - name: sshd - restart service
    service:
      name: "{{ opensshd_init_name[ansible_os_family] }}"
      state: restarted
